maxSkipSpeedPerTick: 40
nightCantBePassedMessage: Никакой отдых не поможет пропустить эту ночь
playersNeededToSkipMessage: Чтобы пропустить ночь, нужно чтобы легло еще %d игрок%s
sleepStatusMessage: §7Спит §r%d§7 из §r%d§7 игроков §8|§7 Время§r %s
timePatternMessage: '%02d§8:§f%02d§7%s'
goodMorningMessage: §7Доброе утро,§f %s
